pub(crate) mod axis;
pub(crate) mod correlation;
pub(crate) mod correlation_matrix;
pub(crate) mod covariance;
pub(crate) mod covariance_matrix;
pub(crate) mod quantile;
pub(crate) mod stddev;
pub(crate) mod variance;
pub(crate) mod weighted;
