[package]
name = "atlas-random"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
atlas-ndarray.workspace = true
num-traits.workspace = true
rand.workspace = true
rand_distr.workspace = true
rayon.workspace = true
thiserror.workspace = true

[lints]
workspace = true
