from collections.abc import Iterable, Sequence
from typing import Any

import numpy as np
from numpy.typing import ArrayLike, DTypeLike, NDArray

from .errors import (
    AtlasError,
    AxisError,
    ModelError,
    NumericError,
    ShapeError,
    SliceError,
)
from .interop import *
from .linalg import *
from .ml import *
from .random import *
from .statistics import *

Array = NDArray[Any]
__version__: str

def asarray(value: ArrayLike, dtype: DTypeLike | None = ...) -> Array: ...
def astype(value: ArrayLike, dtype: DTypeLike, *, copy: bool = ...) -> Array: ...
def zeros(shape: int | Sequence[int], dtype: DTypeLike = ...) -> Array: ...
def ones(shape: int | Sequence[int], dtype: DTypeLike = ...) -> Array: ...
def full(
    shape: int | Sequence[int],
    fill_value: Any = ...,
    *,
    dtype: DTypeLike | None = ...,
    value: Any = ...,
) -> Array: ...
def eye(
    rows: int, columns: int | None = ..., diagonal: int = ..., dtype: DTypeLike = ...
) -> Array: ...
def identity(size: int, dtype: DTypeLike = ...) -> Array: ...
def arange(
    start: Any, stop: Any | None = ..., step: Any = ..., dtype: DTypeLike | None = ...
) -> Array: ...
def linspace(
    start: float,
    stop: float,
    num: int,
    *,
    dtype: DTypeLike | None = ...,
    endpoint: bool = ...,
) -> Array: ...
def zeros_like(value: ArrayLike, *, dtype: DTypeLike | None = ...) -> Array: ...
def ones_like(value: ArrayLike, *, dtype: DTypeLike | None = ...) -> Array: ...
def empty_like(value: ArrayLike, *, dtype: DTypeLike | None = ...) -> Array: ...
def full_like(
    value: ArrayLike, fill_value: Any, *, dtype: DTypeLike | None = ...
) -> Array: ...
def ascontiguousarray(value: ArrayLike, *, dtype: DTypeLike | None = ...) -> Array: ...
def copy(value: ArrayLike) -> Array: ...
def copyto(
    destination: Array, source: ArrayLike | Any, *, where: ArrayLike | bool = ...
) -> None: ...
def shape(value: ArrayLike) -> tuple[int, ...]: ...
def ndim(value: ArrayLike) -> int: ...
def size(value: ArrayLike) -> int: ...
def dtype(value: ArrayLike) -> np.dtype[Any]: ...
def reshape(
    value: ArrayLike, shape: int | Sequence[int], *dimensions: int
) -> Array: ...
def ravel(value: ArrayLike) -> Array: ...
def flatten(value: ArrayLike) -> Array: ...
def squeeze(value: ArrayLike, axis: int | None = ...) -> Array: ...
def expand_dims(value: ArrayLike, axis: int) -> Array: ...
def transpose(value: ArrayLike, axes: Sequence[int] | None = ...) -> Array: ...
def moveaxis(value: ArrayLike, source: int, destination: int) -> Array: ...
def swap_axes(value: ArrayLike, axis1: int, axis2: int) -> Array: ...
def swapaxes(value: ArrayLike, axis1: int, axis2: int) -> Array: ...
def concatenate(
    arrays: Iterable[ArrayLike], axis: int = ..., *, out: Array | None = ...
) -> Array: ...
def stack(
    arrays: Iterable[ArrayLike], axis: int = ..., *, out: Array | None = ...
) -> Array: ...
def split(
    value: ArrayLike, indices_or_sections: int | Sequence[int], axis: int = ...
) -> list[Array]: ...
def repeat(value: ArrayLike, repeats: int, axis: int | None = ...) -> Array: ...
def tile(value: ArrayLike, repetitions: int | Sequence[int]) -> Array: ...
def flip(value: ArrayLike, axis: int | None = ...) -> Array: ...
def roll(value: ArrayLike, shift: int, axis: int | None = ...) -> Array: ...
def pad(
    value: ArrayLike, pad_width: Any, mode: str = ..., constant_values: Any = ...
) -> Array: ...
def broadcast_to(value: ArrayLike, shape: Sequence[int]) -> Array: ...
def broadcast_arrays(*values: ArrayLike) -> tuple[Array, ...]: ...
def atleast_1d(*values: ArrayLike | Any) -> Array | tuple[Array, ...]: ...
def atleast_2d(*values: ArrayLike | Any) -> Array | tuple[Array, ...]: ...
def atleast_3d(*values: ArrayLike | Any) -> Array | tuple[Array, ...]: ...
def add(
    lhs: ArrayLike | Any, rhs: ArrayLike | Any, *, out: Array | None = ...
) -> Array: ...
def subtract(
    lhs: ArrayLike | Any, rhs: ArrayLike | Any, *, out: Array | None = ...
) -> Array: ...
def multiply(
    lhs: ArrayLike | Any, rhs: ArrayLike | Any, *, out: Array | None = ...
) -> Array: ...
def divide(
    lhs: ArrayLike | Any, rhs: ArrayLike | Any, *, out: Array | None = ...
) -> Array: ...
def neg(value: ArrayLike) -> Array: ...
def abs(value: ArrayLike) -> Array: ...
def sign(value: ArrayLike) -> Array: ...
def round(value: ArrayLike, decimals: int = ...) -> Array: ...
def clip(value: ArrayLike, minimum: Any, maximum: Any) -> Array: ...
def matmul(lhs: ArrayLike, rhs: ArrayLike) -> Array: ...
def dot(lhs: ArrayLike, rhs: ArrayLike) -> Array: ...
def equal(lhs: ArrayLike | Any, rhs: ArrayLike | Any) -> Array: ...
def not_equal(lhs: ArrayLike | Any, rhs: ArrayLike | Any) -> Array: ...
def less(lhs: ArrayLike | Any, rhs: ArrayLike | Any) -> Array: ...
def less_equal(lhs: ArrayLike | Any, rhs: ArrayLike | Any) -> Array: ...
def greater(lhs: ArrayLike | Any, rhs: ArrayLike | Any) -> Array: ...
def greater_equal(lhs: ArrayLike | Any, rhs: ArrayLike | Any) -> Array: ...
def bitwise_and(lhs: ArrayLike, rhs: ArrayLike) -> Array: ...
def bitwise_or(lhs: ArrayLike, rhs: ArrayLike) -> Array: ...
def bitwise_xor(lhs: ArrayLike, rhs: ArrayLike) -> Array: ...
def bitwise_not(value: ArrayLike) -> Array: ...
def isnan(value: ArrayLike) -> Array: ...
def isinf(value: ArrayLike) -> Array: ...
def isfinite(value: ArrayLike) -> Array: ...
def where(
    condition: ArrayLike, x: ArrayLike | Any = ..., y: ArrayLike | Any = ...
) -> Array | tuple[Array, ...]: ...
def select(value: ArrayLike, mask: ArrayLike, other: Any = ...) -> Array: ...
def masked_fill(value: ArrayLike, mask: ArrayLike, fill_value: Any) -> Array: ...
def allclose(
    lhs: ArrayLike,
    rhs: ArrayLike,
    *,
    rtol: float = ...,
    atol: float = ...,
    equal_nan: bool = ...,
) -> bool: ...
def sum(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | Any: ...
def mean(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | float: ...
def min(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | Any: ...
def max(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | Any: ...
def all(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | bool: ...
def any(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | bool: ...
def argmin(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | int: ...
def argmax(
    value: ArrayLike, axis: int | None = ..., *, keepdims: bool = ...
) -> Array | int: ...
def cumsum(
    value: ArrayLike, axis: int | None = ..., *, out: Array | None = ...
) -> Array: ...
def cumprod(
    value: ArrayLike, axis: int | None = ..., *, out: Array | None = ...
) -> Array: ...
def sort(value: ArrayLike, axis: int = ...) -> Array: ...
def argsort(value: ArrayLike, axis: int = ...) -> Array: ...
def partition(value: ArrayLike, kth: int | Sequence[int], axis: int = ...) -> Array: ...
def argpartition(
    value: ArrayLike, kth: int | Sequence[int], axis: int = ...
) -> Array: ...
def searchsorted(
    sorted: ArrayLike,
    values: ArrayLike | Any,
    side: str = ...,
    *,
    sorter: ArrayLike | None = ...,
) -> Array | int: ...
def unique(
    value: ArrayLike,
    *,
    axis: None = ...,
    return_index: bool = ...,
    return_inverse: bool = ...,
    return_counts: bool = ...,
) -> Any: ...
def take(
    value: ArrayLike, indices: ArrayLike, axis: int | None = ..., *, mode: str = ...
) -> Array: ...
def put(value: Array, indices: ArrayLike, values: ArrayLike | Any) -> None: ...
def choose(indices: ArrayLike, choices: Sequence[ArrayLike | Any]) -> Array: ...
def nonzero(value: ArrayLike) -> tuple[Array, ...]: ...
def argwhere(value: ArrayLike) -> Array: ...
def result_type(*values: ArrayLike | DTypeLike | Any) -> np.dtype[Any]: ...
def promote_types(left: DTypeLike, right: DTypeLike) -> np.dtype[Any]: ...
def can_cast(source: DTypeLike, target: DTypeLike, *, casting: str = ...) -> bool: ...
def issubdtype(dtype: DTypeLike, kind: DTypeLike) -> bool: ...
def min_scalar_type(value: Any) -> np.dtype[Any]: ...
def finfo(dtype: DTypeLike) -> np.finfo[Any]: ...
def iinfo(dtype: DTypeLike) -> np.iinfo[Any]: ...
def common_type(*values: ArrayLike | Any) -> np.dtype[Any]: ...
def all_axis(value: ArrayLike, axis: int) -> Array: ...
def any_axis(value: ArrayLike, axis: int) -> Array: ...
def sum_axis(value: ArrayLike, axis: int, *, out: Array | None = ...) -> Array: ...
def mean_axis(value: ArrayLike, axis: int, *, out: Array | None = ...) -> Array: ...
def min_axis(value: ArrayLike, axis: int, *, out: Array | None = ...) -> Array: ...
def max_axis(value: ArrayLike, axis: int, *, out: Array | None = ...) -> Array: ...
def argmin_axis(value: ArrayLike, axis: int) -> Array: ...
def argmax_axis(value: ArrayLike, axis: int) -> Array: ...
def cumsum_axis(value: ArrayLike, axis: int, *, out: Array | None = ...) -> Array: ...
def cumprod_axis(value: ArrayLike, axis: int, *, out: Array | None = ...) -> Array: ...
def nanmin(value: ArrayLike) -> float: ...
def nanmax(value: ArrayLike) -> float: ...
def nanmean(value: ArrayLike) -> float: ...
def nanstd(value: ArrayLike, ddof: int = ...) -> float: ...
def count_true(value: ArrayLike) -> int: ...
def shares_memory(
    left: ArrayLike, right: ArrayLike, *, max_work: int | None = ...
) -> bool: ...
def may_share_memory(
    left: ArrayLike, right: ArrayLike, *, max_work: int | None = ...
) -> bool: ...
def var(value: ArrayLike, *, ddof: int = ...) -> float: ...
def std(value: ArrayLike, *, ddof: int = ...) -> float: ...
