from typing import Any
from numpy.typing import ArrayLike, NDArray

Array = NDArray[Any]

def to_arrow_primitive(value: ArrayLike) -> Any: ...
def from_arrow_primitive(value: Any) -> Array: ...
def to_arrow_record_batch(matrix: ArrayLike, column_names: list[str]) -> Any: ...
def from_arrow_record_batch(value: Any) -> Array: ...
