from typing import Any
from numpy.typing import ArrayLike, NDArray

Array = NDArray[Any]

class ConjugateGradientResult:
    @property
    def solution(self) -> Array: ...
    @property
    def iterations(self) -> int: ...
    @property
    def residual_norm(self) -> float: ...
    @property
    def converged(self) -> bool: ...
    @property
    def dtype(self) -> Any: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    def __len__(self) -> int: ...

def norm(value: ArrayLike, order: int | float = ...) -> float: ...
def trace(value: ArrayLike, offset: int = ...) -> Any: ...
def diag(value: ArrayLike, k: int = ...) -> Array: ...
def matrix_norm(value: ArrayLike, order: str = ...) -> float: ...
def det(value: ArrayLike) -> float: ...
def slogdet(value: ArrayLike) -> tuple[float, float]: ...
def inverse(value: ArrayLike) -> Array: ...
def solve(matrix: ArrayLike, rhs: ArrayLike) -> Array: ...
def solve_transpose(matrix: ArrayLike, rhs: ArrayLike) -> Array: ...
def cholesky(value: ArrayLike) -> Array: ...
def solve_spd(matrix: ArrayLike, rhs: ArrayLike) -> Array: ...
def qr(value: ArrayLike) -> tuple[Array, Array]: ...
def least_squares(matrix: ArrayLike, rhs: ArrayLike) -> Array: ...
def matrix_rank(value: ArrayLike) -> int: ...
def symmetric_eigendecomposition(value: ArrayLike) -> tuple[Array, Array]: ...
def conjugate_gradient(
    matrix: ArrayLike, rhs: ArrayLike, max_iterations: int, tolerance: float
) -> ConjugateGradientResult: ...
