from typing import Any, Iterator, Mapping
from numpy.typing import ArrayLike, NDArray

Array = NDArray[Any]

class _Estimator:
    is_fitted: bool
    def get_params(self, deep: bool = ...) -> dict[str, Any]: ...
    def set_params(self, **kwargs: Any) -> _Estimator: ...
    def copy(self) -> _Estimator: ...

class LinearRegression:
    is_fitted: bool
    intercept_: float
    coef_: Array
    def fit(self, features: ArrayLike, targets: ArrayLike) -> LinearRegression: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def score(self, features: ArrayLike, targets: ArrayLike) -> float: ...

class RidgeRegression(_Estimator):
    l2_regularization: float
    intercept_: float
    coef_: Array
    def __init__(self, l2_regularization: float = ...) -> None: ...
    def fit(self, features: ArrayLike, targets: ArrayLike) -> RidgeRegression: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def score(self, features: ArrayLike, targets: ArrayLike) -> float: ...

class BinaryLogisticRegression(_Estimator):
    intercept_: float
    coef_: Array
    def __init__(
        self,
        learning_rate: float = ...,
        max_iterations: int = ...,
        convergence_tolerance: float = ...,
        l2_regularization: float = ...,
    ) -> None: ...
    def fit(
        self, features: ArrayLike, labels: ArrayLike
    ) -> BinaryLogisticRegression: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def predict_proba(self, features: ArrayLike) -> Array: ...
    def fit_predict(self, features: ArrayLike, labels: ArrayLike) -> Array: ...
    def score(self, features: ArrayLike, labels: ArrayLike) -> float: ...

class BinaryPerceptron(_Estimator):
    intercept_: float
    coef_: Array
    def __init__(
        self,
        learning_rate: float = ...,
        max_iterations: int = ...,
        shuffle_seed: int | None = ...,
    ) -> None: ...
    def fit(self, features: ArrayLike, labels: ArrayLike) -> BinaryPerceptron: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def fit_predict(self, features: ArrayLike, labels: ArrayLike) -> Array: ...

class GaussianNaiveBayes(_Estimator):
    variance_smoothing: float
    def __init__(self, variance_smoothing: float = ...) -> None: ...
    def fit(self, features: ArrayLike, labels: ArrayLike) -> GaussianNaiveBayes: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def predict_proba(self, features: ArrayLike) -> Array: ...
    def fit_predict(self, features: ArrayLike, labels: ArrayLike) -> Array: ...

class KnnClassifier(_Estimator):
    def __init__(
        self,
        k: int,
        search_algorithm: str = ...,
        weighting: str = ...,
        tree_leaf_size: int = ...,
    ) -> None: ...
    def fit(self, features: ArrayLike, labels: ArrayLike) -> KnnClassifier: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def predict_proba(self, features: ArrayLike) -> Array: ...
    def fit_predict(self, features: ArrayLike, labels: ArrayLike) -> Array: ...

class KnnRegressor(_Estimator):
    def __init__(
        self,
        k: int,
        search_algorithm: str = ...,
        weighting: str = ...,
        tree_leaf_size: int = ...,
    ) -> None: ...
    def fit(self, features: ArrayLike, targets: ArrayLike) -> KnnRegressor: ...
    def predict(self, features: ArrayLike) -> Array: ...

class NearestCentroidClassifier:
    is_fitted: bool
    def fit(
        self, features: ArrayLike, labels: ArrayLike
    ) -> NearestCentroidClassifier: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def fit_predict(self, features: ArrayLike, labels: ArrayLike) -> Array: ...

class DecisionStumpClassifier:
    is_fitted: bool
    def fit(
        self, features: ArrayLike, labels: ArrayLike
    ) -> DecisionStumpClassifier: ...
    def predict(self, features: ArrayLike) -> Array: ...
    def fit_predict(self, features: ArrayLike, labels: ArrayLike) -> Array: ...

class StandardScaler:
    is_fitted: bool
    mean_: Array
    scale_: Array
    def fit(self, features: ArrayLike) -> StandardScaler: ...
    def fit_transform(self, features: ArrayLike) -> Array: ...
    def transform(self, features: ArrayLike) -> Array: ...
    def inverse_transform(self, features: ArrayLike) -> Array: ...

class MinMaxScaler(_Estimator):
    output_minimum: float
    output_maximum: float
    data_min_: Array
    data_max_: Array
    def __init__(
        self, output_minimum: float = ..., output_maximum: float = ...
    ) -> None: ...
    def fit(self, features: ArrayLike) -> MinMaxScaler: ...
    def fit_transform(self, features: ArrayLike) -> Array: ...
    def transform(self, features: ArrayLike) -> Array: ...
    def inverse_transform(self, features: ArrayLike) -> Array: ...

class ConfusionMatrix:
    classes: Array
    counts: Array
    dtype: Any
    shape: tuple[int, ...]
    ndim: int
    def __len__(self) -> int: ...

class ClassificationReport(Mapping[str, float]):
    accuracy: float
    precision: float
    recall: float
    f1_score: float
    def __getitem__(self, key: str) -> float: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class BinaryGiniSplit:
    impurity: float
    left_count: int
    right_count: int
    def __len__(self) -> int: ...

class TrainTestSplit:
    train_features: Array
    train_targets: Array
    test_features: Array
    test_targets: Array
    def __iter__(self) -> Iterator[Array]: ...
    def __len__(self) -> int: ...

class KFold:
    train_indices: Array
    validation_indices: Array
    def __iter__(self) -> Iterator[Array]: ...
    def __len__(self) -> int: ...

def accuracy(actual: ArrayLike, predicted: ArrayLike) -> float: ...
def log_loss(actual: ArrayLike, probabilities: ArrayLike) -> float: ...
def mean_absolute_error(actual: ArrayLike, predicted: ArrayLike) -> float: ...
def mean_squared_error(actual: ArrayLike, predicted: ArrayLike) -> float: ...
def r_squared(actual: ArrayLike, predicted: ArrayLike) -> float: ...
def confusion_matrix(actual: ArrayLike, predicted: ArrayLike) -> ConfusionMatrix: ...
def classification_report(
    actual: ArrayLike, predicted: ArrayLike
) -> ClassificationReport: ...
def evaluate_binary_gini_split(
    feature_values: ArrayLike, labels: ArrayLike, threshold: float
) -> BinaryGiniSplit: ...
def train_test_split(
    features: ArrayLike, targets: ArrayLike, *, test_ratio: float = ..., seed: int = ...
) -> TrainTestSplit: ...
def k_fold_split(
    features: ArrayLike, fold_count: int, *, seed: int = ...
) -> list[KFold]: ...
def stratified_k_fold_split(
    features: ArrayLike, labels: ArrayLike, fold_count: int, *, seed: int = ...
) -> list[KFold]: ...
