from typing import Any
from numpy.typing import ArrayLike, NDArray

Array = NDArray[Any]

class GeneratorState: ...

class Generator:
    def __init__(self, seed: int) -> None: ...
    def get_state(self) -> GeneratorState: ...
    def set_state(self, state: GeneratorState) -> None: ...
    def random(self, shape: int | tuple[int, ...]) -> Array: ...
    def randn(self, shape: int | tuple[int, ...]) -> Array: ...
    def uniform(
        self, shape: int | tuple[int, ...], low: float = ..., high: float = ...
    ) -> Array: ...
    def normal(
        self, shape: int | tuple[int, ...], mean: float = ..., stddev: float = ...
    ) -> Array: ...
    def randint(self, shape: int | tuple[int, ...], low: int, high: int) -> Array: ...
    def bernoulli(
        self, shape: int | tuple[int, ...], probability: float = ...
    ) -> Array: ...
    def categorical(
        self, shape: int | tuple[int, ...], weights: ArrayLike
    ) -> Array: ...
    def choice(self, values: ArrayLike, sample_count: int) -> Array: ...
    def permutation(self, size: int) -> Array: ...
    def shuffle(self, values: ArrayLike, axis: int = ...) -> Array: ...

def default_rng(seed: int = ...) -> Generator: ...
def seeded_rng(seed: int) -> Generator: ...
