from typing import Any
from numpy.typing import ArrayLike, NDArray

Array = NDArray[Any]

def variance(value: ArrayLike, *, ddof: int = ...) -> float: ...
def stddev(value: ArrayLike, *, ddof: int = ...) -> float: ...
def kurtosis(value: ArrayLike) -> float: ...
def skewness(value: ArrayLike) -> float: ...
def median(value: ArrayLike) -> float: ...
def quantile(value: ArrayLike, q: float, *, interpolation: str = ...) -> float: ...
def median_axis(value: ArrayLike, axis: int) -> Array: ...
def quantile_axis(
    value: ArrayLike, q: float, axis: int, *, interpolation: str = ...
) -> Array: ...
def weighted_mean(values: ArrayLike, weights: ArrayLike) -> float: ...
def weighted_variance(values: ArrayLike, weights: ArrayLike) -> float: ...
def covariance(left: ArrayLike, right: ArrayLike) -> float: ...
def correlation(left: ArrayLike, right: ArrayLike) -> float: ...
def covariance_matrix(value: ArrayLike) -> Array: ...
def correlation_matrix(value: ArrayLike) -> Array: ...
